---
abstract: "Quickly mock objects and classes, even temporarily replace them,\nside-effect free."
author:
  - 'Chad Granum <exodist7@gmail.com>'
build_requires:
  Fennec::Lite: 0.004
  Test::Exception: 0.29
  Test::Simple: 0.88
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mock-Quick
provides:
  Mock::Quick:
    file: lib/Mock/Quick.pm
    version: 1.103
  Mock::Quick::Class:
    file: lib/Mock/Quick/Class.pm
    version: 0
  Mock::Quick::Method:
    file: lib/Mock/Quick/Method.pm
    version: 0
  Mock::Quick::Object:
    file: lib/Mock/Quick/Object.pm
    version: 0
  Mock::Quick::Object::Control:
    file: lib/Mock/Quick/Object/Control.pm
    version: 0
  Mock::Quick::Util:
    file: lib/Mock/Quick/Util.pm
    version: 0
  Object::Quick:
    file: lib/Object/Quick.pm
    version: 0
requires:
  Carp: 0
  Exporter::Declare: 0.103
  Scalar::Util: 0
resources:
  bugtracker: http://github.com/exodist/Object-Quick/issues
  homepage: http://open-exodus.net/projects/Object-Quick
  license: http://dev.perl.org/licenses/
  repository: http://github.com/exodist/Object-Quick
version: 1.103
