---
abstract: 'Quickly mock objects and classes, even temporarily replace them,'
author:
  - 'Chad Granum <exodist7@gmail.com>'
build_requires:
  Fennec::Lite: 0.004
  Test::Exception: 0.29
  Test::Simple: 0.88
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mock-Quick
provides:
  Mock::Quick:
    file: lib/Mock/Quick.pm
    version: 1.105
  Mock::Quick::Class:
    file: lib/Mock/Quick/Class.pm
    version: 0
  Mock::Quick::Method:
    file: lib/Mock/Quick/Method.pm
    version: 0
  Mock::Quick::Object:
    file: lib/Mock/Quick/Object.pm
    version: 0
  Mock::Quick::Object::Control:
    file: lib/Mock/Quick/Object/Control.pm
    version: 0
  Mock::Quick::Util:
    file: lib/Mock/Quick/Util.pm
    version: 0
  Object::Quick:
    file: lib/Object/Quick.pm
    version: 0
requires:
  Carp: 0
  Exporter::Declare: 0.103
  Scalar::Util: 0
resources:
  bugtracker: http://github.com/exodist/Mock-Quick/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/exodist/Mock-Quick
version: 1.105
